# Skill Nexis Internship - Week 1
## Assignment 3: Categorical Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
data = {
    "Name": ["Ali", "Rahul", "Sara", "John", "Aisha"],
    "Gender": ["Male", "Male", "Female", "Male", "Female"]
}

df = pd.DataFrame(data)

df

    Name  Gender
0    Ali    Male
1  Rahul    Male
2   Sara  Female
3   John    Male
4  Aisha  Female

In [3]:
label_encoder = LabelEncoder()

df["Gender_encoded"] = label_encoder.fit_transform(df["Gender"])

df

    Name  Gender  Gender_encoded
0    Ali    Male               1
1  Rahul    Male               1
2   Sara  Female               0
3   John    Male               1
4  Aisha  Female               0

In [4]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[["Gender"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["Gender"])
)

encoded_df

   Gender_Female  Gender_Male
0            0.0          1.0
1            0.0          1.0
2            1.0          0.0
3            0.0          1.0
4            1.0          0.0